language: node_js
node_js:
  - 0.8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g karma
  - npm install
  - bower install
  - grunt exec:run-server
  - sleep 1 # give server time to start

script:
  - grunt karma:unit
  - grunt karma:e2e
  - grunt jshint