env:
  global:
    - secure: "OxoOy4Tz+pOgi1Wc0r2EctA3pppBbp8HftyEgpYo0uTvWus5TVmksZ4M5VxxOmx6lqyUG6zYwUPd4HlX/xwwdhBzp+Ba/ZtZPNteTtDG/ZhFUhIegANm7xq5CauFu0QdVBpjim3dFQfvpV8+3pui9oV38K5Z2ScKLLZrljmJKpE="
    - secure: "YFiUIpdh/UrxhcedVQvYhSrcQ2rj8JeGmZdAauRwUo7NqfMOeV1tz36q5SW9Ed0cCE0Cs/z2SyYCVe9qRdWGr5BaTzUp4JlaKz3yt3viA+2vNVhvQSUhTDdt/oS0rsUUFKrewdobl2hvlEq7+9a0NGHNaPJIdApczW/wEUqO2os="

addons:
  sauce_connect: true

language: node_js
node_js:
  - 0.8

before_script:
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g bower
  - npm install --quiet -g karma
  - npm install --quiet -g protractor
  - npm install --quiet -g grunt-cli
  - npm install
  - bower install
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - grunt exec:run-server
  - sleep 20 # give server time to start

script:
  - grunt karma:unit
  - grunt protractor
  - grunt jshint